apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: falco
  namespace: falco
spec:
  chart:
    spec:
      chart: falco
      sourceRef:
        kind: HelmRepository
        name: falcosecurity
        namespace: falco
  interval: 1m0s
  values:
    tty: true
    falcosidekick:
      enabled: true
      webui:
        enabled: true
