---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ww-gitops
  namespace: flux-system
spec:
  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: ww-gitops
  interval: 1m0s
  values:
    adminUser:
      create: true
      username: admin
      passwordHash: $2a$12$hV9c8CoX4f8K3b8HvD0r3OJ7qTey91HUu2CyuYOi8UNZAsWfdH0ZO
    ingress:
      enabled: true
