---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  chart:
    spec:
      chart: loki-simple-scalable
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 1m0s
  install:
    remediation:
      retries: 3
  values:
    write:
      persistence:
        size: 2Gi
    read:
      persistence:
        size: 2Gi
    singleBinary:
      persistence:
        size: 2Gi
