---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  chart:
    spec:
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 1m0s
  install:
    remediation:
      retries: 3
  values:
    grafana:
      enabled: false
    loki:
      persistence:
        enabled: true
        accessModes:
          - ReadWriteOnce
        size: 5Gi
      service:
        labels:
          - scrape-service-metrics: "true"
      serviceMonitor:
        enabled: true
        interval: 15s
