apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  chart:
    spec:
      chart: longhorn
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: longhorn-system
  interval: 1m0s
  install:
    remediation:
      retries: 3
  values:
    service:
      ui:
        type: ClusterIP
      manager:
        type: ClusterIP
    persistence:
      defaultFsType: ext4
    ingress:
      enabled: true
      host: longhorn.example.tld
      tls: false
    defaultSettings:
      deletingConfirmationFlag: true
    metrics:
      serviceMonitor:
        enabled: true
