---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: blackbox-exporter
  namespace: flux-system
spec:
  dependsOn:
    - name: kube-prometheus-stack
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: catalogue
  path: "./infrastructure/blackbox-exporter"
  prune: true
  validation: client
