apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-config
  namespace: flux-system
spec:
  dependsOn:
    - name: metallb
    - name: external-secrets
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: catalogue
  path: ./clusters/angerboda/config
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
