apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-config-metalb
  namespace: flux-system
spec:
  dependsOn:
    - name: metallb
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: catalogue
  path: ./clusters/angerboda/config/metalb
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-config-clustersecretstore
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: catalogue
  path: ./clusters/angerboda/config/clustersecretstore
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-config-externalsecrets
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-config-clustersecretstore
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: catalogue
  path: ./clusters/angerboda/config/externalsecrets
  prune: true
