---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: catalogue
  path: "./infrastructure/external-dns"
  prune: true
  validation: client
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  patches:
    - patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2beta1
        kind: HelmRelease
        metadata:
          name: external-dns
          namespace: external-dns
        spec:
          values:
            txtOwnerId: angerboda-anyops
      target:
        kind: HelmRelease
        name: external-dns
        namespace: external-dns
