apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  dependsOn:
    - name: prometheus-operator-crds
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: catalogue
  path: ./infrastructure/external-secrets
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
