apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: falco
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: catalogue
  path: ./infrastructure/falco
  prune: true
