---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: loki-stack
  namespace: flux-system
spec:
  dependsOn:
    - name: longhorn
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: catalogue
  path: "./infrastructure/loki-stack"
  prune: true
  validation: client
  patches:
    - patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2beta1
        kind: HelmRelease
        metadata:
          name: loki
          namespace: loki-system
        spec:
          values:
            grafana:
              ingress:
                enabled: true
                hosts:
                  - loki.angerboda.anyops.site
                tls: []
                annotations:
                  external-dns.alpha.kubernetes.io/target: traefik.angerboda.anyops.site
              grafana.ini:
                server:
                  domain: loki.angerboda.anyops.site
                  root_url: http://loki.angerboda.anyops.site/
      target:
        kind: HelmRelease
        name: loki
        namespace: loki-system
