---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: longhorn
  namespace: flux-system
spec:
  dependsOn:
    - name: traefik
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: catalogue
  path: "./infrastructure/longhorn"
  prune: true
  validation: client
  patches:
    - patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2beta1
        kind: HelmRelease
        metadata:
          name: longhorn
          namespace: longhorn-system
        spec:
          values:
            ingress:
              enabled: true
              host: longhorn.angerboda.anyops.site
              tls: false
              annotations:
                external-dns.alpha.kubernetes.io/target: angerboda.anyops.site
      target:
        kind: HelmRelease
        name: longhorn
        namespace: longhorn-system
