---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: longhorn
  namespace: flux-system
spec:
  dependsOn:
    - name: traefik
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: catalogue
  path: "./infrastructure/longhorn"
  prune: true
  validation: client
  patches:
    - patch: |-
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          name: longhorn-ingress
        spec:
          rules:
            - host: longhorn.angerboda.anyops.site
      target:
        kind: Ingress
        name: longhorn-ingress
        namespace: longhorn-system
