---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: minio-operator
  namespace: flux-system
spec:
  dependsOn:
    - name: longhorn
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: catalogue
  path: "./infrastructure/minio-operator"
  prune: true
  validation: client
  patches:
    - patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2beta1
        kind: HelmRelease
        metadata:
          name: minio-operator
          namespace: minio-operator
        spec:
          values:
            console:
              ingress:
                enabled: true
                host: minio-console.angerboda.anyops.site
                tls: []
                annotations:
                  external-dns.alpha.kubernetes.io/target: traefik.angerboda.anyops.site
      target:
        kind: HelmRelease
        name: minio-operator
        namespace: minio-operator
