---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: traefik
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: catalogue
  path: "./infrastructure/traefik"
  prune: true
  validation: client
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  patches:
    - patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2beta1
        kind: HelmRelease
        metadata:
          name: traefik
          namespace: traefik
        spec:
          values:
            ingressRoute:
              dashboard:
                enabled: false
            service:
              annotations:
                external-dns.alpha.kubernetes.io/hostname: traefik.angerboda.anyops.site
                metallb.universe.tf/address-pool: lb-pool
      target:
        kind: HelmRelease
        name: traefik
        namespace: traefik
