apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: trivy-operator
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure
    - name: prometheus-operator-crds
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: catalogue
  path: ./infrastructure/trivy-operator
  prune: true
