---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lb-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.1.200/29
    - 192.168.1.208/28
    - 192.168.1.224/28
    - 192.168.1.240/32
