---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  values:
    prometheus:
      serviceMonitor:
        enabled: true
  interval: 1m0s
  install:
    remediation:
      retries: 3
