---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - namespace.yaml
  - secret-sops-encrypted.yaml
  - release.yaml
  #- service.yaml
  - middleware.yaml
