apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
  interval: 1m0s
  install:
    remediation:
      retries: 3
  values:
    deployment:
      enabled: true
      kind: DaemonSet
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: "Host(`traefik.example.tld`) && PathPrefix(`/api`, `/dashboard`)"
        entryPoints: ["traefik", "web"]
        #middlewares:
        #  - name: "traefik-dashboard-auth"
        #    namespace: traefik
    service:
      enabled: true
      type: LoadBalancer
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "traefik.example.tld"
      labels:
        scrape-service-metrics: "true"
      spec:
        externalTrafficPolicy: Local
    ports:
      traefik:
        expose: true
        nodePort: 32090
      web:
        expose: true
        nodePort: 32080
      websecure:
        expose: true
        nodePort: 32443
    globalArguments:
      - "--global.checknewversion"
      - "--entryPoints.web.forwardedHeaders.insecure"
    additionalArguments:
      - "--metrics.prometheus"
    logs:
      general:
        level: ERROR
        format: json
      access:
        enabled: true
        filters:
          statuscodes: "300-399,400-499,500-599"
    providers:
      kubernetesIngress:
        enabled: true
        publishedService:
          enabled: true
    metrics:
      prometheus:
        entryPoint: metrics
        service:
          enabled: true
        serviceMonitor:
          jobLabel: traefik
          honorLabels: true
