---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  interval: 1m0s
  install:
    remediation:
      retries: 3
  values:
    deployment:
      enabled: true
      kind: DaemonSet
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: "Host(`traefik.anyops.site`) && PathPrefix(`/api`, `/dashboard`)"
        entryPoints: ["traefik", "web"]
        middlewares:
          - name: "traefik-dashboard-auth"
    service:
      enabled: true
      type: NodePort
      labels:
        scrape-service-metrics: "true"
      spec:
        externalTrafficPolicy: Cluster
    ports:
      traefik:
        expose: true
        nodePort: 32090
      web:
        nodePort: 32080
      websecure:
        expose: true
        nodePort: 32443
      metrics:
        port: 9100
        expose: true
        exposedPort: 9100
        protocol: TCP
    globalArguments:
      - "--global.checknewversion"
      - "--entryPoints.web.forwardedHeaders.insecure"
    additionalArguments:
      - "--metrics.prometheus"
    logs:
      general:
        level: ERROR
        format: json
      access:
        enabled: true
        filters:
          statuscodes: "300-399,400-499,500-599"
    providers:
      kubernetesIngress:
        enabled: true
    metrics:
      prometheus:
        entryPoint: metrics
