apiVersion: v1
data:
    password: ENC[AES256_GCM,data:KASi75yoIrDorvk6GKp0aMMYCbahZ5lLsNvSXmIYCUKLgSG6qmyYjdjVKU8=,iv:+ZII1gKyAtNRgTrg09P7kCVsNM6qKJxYSUZ9EphfahA=,tag:ODQDJkMmSnM4iQvDhT/XuQ==,type:str]
    username: ENC[AES256_GCM,data:Gm43rD+qtVU=,iv:MCx3ms559rs3M5ARFciVC+2j7EUpLNVTODd4pBWSDxY=,tag:bDyHkteQ+7ktL2g0SQYZZg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: traefik-dashboard-auth
    namespace: traefik
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age193946r4cjdpejxe5h0kcrt9vcd8cgy0wanjqtxyunct0zjsjqq0sh3zha8
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwMTU2NFNTRWdzK0tnVjJq
              NHovRjFIbnNPekpwQjVMMmFWQVBDcSswQWdzClJ5Z1hySzhWZEtyTzBrT09WQ0Ro
              dkxKRkFWSVBoSmVvbzMyZFhhY0tjRVkKLS0tIFgxWkN4TzAzRVNNSEkyMUNLcTdh
              VlhSV0wxRXFQUHBkWGFscXRpeVlnbnMK88YAOYq+cLB7XerdKNOTJ2WSULa5qWDF
              JqyuUL9LM5jfBRjsAIi7SLN31W2dJQ1WoqLokWQFtAZG2S0itCN7sw==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-20T21:19:49Z"
    mac: ENC[AES256_GCM,data:lhICbvt5X/3PDfJkmpPPOwLvmYkZMpWdRRUG9FZcVPj8AqxQ+buOtcZ45jlcFnkXaRH2MJqubDlIXl94fjE+NDkLfXQ8Jl66h1HrbOt0SMk/X0dVUaSkK0pZZEQmdf4cW2upmEPgmZtfzN+AjFz6kyWvEaWzjMoV0OqAsOf9URo=,iv:udGFURRqdBk6tDu4KmHJf51ruwqio4KBj9X3Wd5lCcw=,tag:XmZVyWQk6IKZjSw8fvY/MQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
