---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: redis
spec:
  chart:
    spec:
      chart: redis
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 1m0s
  install:
    remediation:
      retries: 3
  values:
    master:
      service:
        type: LoadBalancer
        #loadBalancerIP: 192.168.1.240
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "redis.anyops.site"
    auth:
      existingSecret: redis-auth
