---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: redis
spec:
  chart:
    spec:
      chart: redis
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 1m0s
  install:
    remediation:
      retries: 3
  values:
    master:
      persistence:
        enabled: true
        mountPath: /data
        accessModes:
          - ReadWriteOnce
        size: 2Gi
      service:
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "redis.anyops.site"
    replica:
      persistence:
        enabled: true
        mountPath: /data
        accessModes:
          - ReadWriteOnce
        size: 2Gi
    auth:
      existingSecret: redis-auth
