---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-tenant
  namespace: minio-tenant
spec:
  chart:
    spec:
      chart: tenant
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
  interval: 1m0s
  install:
    remediation:
      retries: 3
  values:
    tenant:
      name: minio1
      configuration:
        name: minio1-env-configuration
      pools:
        - servers: 0
          name: pool-0
          volumesPerServer: 4
          size: 1Gi
          storageClassName: standard
      mountPath: /export
      subPath: /data
      metrics:
        enabled: true
        port: 9000
        protocol: http
