apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns
  namespace: external-dns
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: external-dns
    creationPolicy: Owner
  data:
    - secretKey: digitalocean_api_token
      remoteRef:
        key: digitalocean_api_token
