---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  interval: 1m0s
  install:
    remediation:
      retries: 3
  values:
    commonLabels:
      scrape-service-metrics: "true"
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: "/metrics/cluster"
      prometheus.io/port: "9000"
    serviceMonitor:
      enabled: true
    txtOwnerId: example-tld
    sources:
      - ingress
      - service
    provider: digitalocean
    digitalocean:
      secretName: external-dns
    env:
      - name: DO_TOKEN
        valueFrom:
          secretKeyRef:
            name: external-dns
            key: digitalocean_api_token
            optional: false
    domainFilters:
      - example.tld
    logLevel: debug
    policy: sync
    resources:
      limits:
        memory: 64Mi
      requests:
        memory: 64Mi
        cpu: 10m
