---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 1m0s
  install:
    remediation:
      retries: 3
  values:
    txtOwnerId: anyops
    replicas: 1
    sources:
      - ingress
      - service
    provider: digitalocean
    digitalocean:
      secretName: external-dns
    domainFilters:
      - anyops.site
      - anyops.dev
    logLevel: debug
    policy: sync
    resources:
      limits:
        memory: 64Mi
      requests:
        memory: 64Mi
        cpu: 10m
