---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  interval: 1m0s
  install:
    remediation:
      retries: 3
  values:
    defaultRules:
      rules:
        etcd: false
        kubeScheduler: false
    alertmanager:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeControllerManager:
      enabled: false
    kubeProxy:
      enabled: false
    prometheus:
      additionalServiceMonitors:
        - name: "monitoring-metrics"
          selector:
            matchLabels:
              scrape-service-metrics: "true"
          namespaceSelector:
            any: true
          endpoints:
            - path: /metrics
              port: metrics
            - path: /metrics
              port: admin
            - path: /metrics
              port: http
            - path: /metrics
              port: http-metrics
    grafana:
      grafana.ini:
        auth.anonymous:
          enabled: true
        metrics:
          enabled: true
        server:
          domain: grafana.develix.local
          root_url: http://grafana.anyops.dev/
      plugins:
        - grafana-polystat-panel
