apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: chaoskube
  namespace: chaoskube
spec:
  chart:
    spec:
      chart: chaoskube
      sourceRef:
        kind: HelmRepository
        name: chaoskube
        namespace: chaoskube
  interval: 1m0s
  install:
    remediation:
      retries: 3
