---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chaoskube
  namespace: chaoskube
spec:
  chart:
    spec:
      chart: chaoskube
      sourceRef:
        kind: HelmRepository
        name: chaoskube
        namespace: flux-system
  values:
    metrics:
      serviceMonitor:
        enabled: true
  interval: 1m0s
  install:
    remediation:
      retries: 3
