---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: minio-operator
spec:
  chart:
    spec:
      chart: operator
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
  interval: 1m0s
  install:
    remediation:
      retries: 3
  values:
    console:
      ingress:
        enabled: true
        host: minio.example.tld
        tls: []
