---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  interval: 1m0s
  install:
    remediation:
      retries: 3
  values:
    defaultRules:
      rules:
        etcd: false
        kubeScheduler: false
    alertmanager:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeControllerManager:
      enabled: false
    kubeProxy:
      enabled: false
    prometheus:
      ingress:
        enabled: true
        hosts:
          - prometheus.example.tld
        tls: []
      additionalServiceMonitors:
        - name: "monitoring-metrics"
          selector:
            matchLabels:
              scrape-service-metrics: "true"
          namespaceSelector:
            any: true
          endpoints:
            - path: /metrics
              port: metrics
            - path: /metrics
              port: admin
            - path: /metrics
              port: http
            - path: /metrics
              port: http-metrics
    grafana:
      datasources:
        datasources.yaml:
          apiVersion: 1
          datasources:
            - name: Prometheus
              type: prometheus
              access: proxy
              url: http://kube-prometheus-stack-prometheus:9090
            - name: Loki
              type: loki
              access: proxy
              url: http://loki.loki-system:3100
              jsonData:
                maxLines: 1000
      admin:
        existingSecret: "grafana-auth"
        userKey: admin-user
        passwordKey: admin-password
      ingress:
        enabled: true
        hosts:
          - grafana.example.tld
        tls: []
      grafana.ini:
        auth.anonymous:
          enabled: false
        metrics:
          enabled: true
        server:
          domain: grafana.example.tld
          root_url: http://grafana.example.tld/
      plugins:
        - grafana-polystat-panel
