---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: minio-system
spec:
  chart:
    spec:
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 1m0s
  install:
    remediation:
      retries: 3
  values:
    persistence:
      enabled: true
      mountPath: /data
      accessModes:
        - ReadWriteOnce
      size: 2Gi
    metrics:
      prometheusAuthType: public
      serviceMonitor:
        enabled: true
    prometheusRule:
      enabled: true
    auth:
      existingSecret: minio-auth
