---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  dependsOn:
    - name: longhorn
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: catalogue
  path: "./infrastructure/kube-prometheus-stack"
  prune: true
  validation: client
  decryption:
    provider: sops
    secretRef:
      name: sops-age
