---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  dependsOn:
    - name: longhorn
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: catalogue
  path: "./infrastructure/kube-prometheus-stack"
  prune: true
  validation: client
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  patches:
    - patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2beta1
        kind: HelmRelease
        metadata:
          name: kube-prometheus-stack
          namespace: monitoring
        spec:
          values:
            grafana:
              grafana.ini:
                server:
                  domain: grafana.odin.anyops.site
                  root_url: http://grafana.odin.anyops.site/
      target:
        kind: HelmRelease
        name: kube-prometheus-stack
        namespace: monitoring
