apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: loki-stack
  namespace: flux-system
spec:
  dependsOn:
    - name: longhorn
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: catalogue
  path: "./infrastructure/loki-stack"
  prune: true
  validation: client
