apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prometheus-blackbox-exporter
  namespace: blackbox-exporter
spec:
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: blackbox-exporter
  interval: 1m0s
  install:
    remediation:
      retries: 3
  values:
    serviceMonitor:
      enabled: true
      selfMonitor:
        enabled: true
        path: /metrics
    service:
      labels:
        scrape-service-metrics: "true"
      annotations:
        prometheus.io/scrape: "true"
