apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-blackbox-exporter
  namespace: blackbox-exporter
spec:
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: blackbox-exporter
  interval: 1m0s
  install:
    remediation:
      retries: 3
  values:
    serviceMonitor:
      selfMonitor:
        enabled: true
        labels:
          foo: bar
        path: /metrics
      enabled: false
    service:
      annotations:
        prometheus.io/scrape: "true"
