---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-blackbox-exporter
  namespace: blackbox-exporter
spec:
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    service:
      labels:
        scrape-service-metrics: "true"
    serviceMonitor:
      enabled: true
      selfMonitor:
        enabled: true
        additionalMetricsRelabels: {}
        additionalRelabeling: []
        labels: {}
        path: /metrics
        interval: 30s
        scrapeTimeout: 30s
  interval: 1m0s
  install:
    remediation:
      retries: 3
