apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: trivy-operator
  namespace: trivy-system
spec:
  chart:
    spec:
      chart: trivy-operator
      sourceRef:
        kind: HelmRepository
        name: trivy-operator
        namespace: trivy-system
  interval: 1m0s
  values:
    service:
      headless: false
    serviceMonitor:
      enabled: true
      namespace: trivy-system
    trivy:
      ignoreUnfixed: true
    operator:
      labels:
        scrape-service-metrics: "true"
