apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: trivy-operator
  namespace: trivy-system
spec:
  chart:
    spec:
      chart: trivy-operator
      sourceRef:
        kind: HelmRepository
        name: trivy-operator
        namespace: trivy-system
  interval: 1m0s
  values:
    serviceMonitor:
      enabled: true
    trivy:
      ignoreUnfixed: true
