apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: trivy-operator
  namespace: trivy-system
spec:
  interval: 1h0m0s
  url: https://aquasecurity.github.io/helm-charts/
