apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: loki
  namespace: loki-system
spec:
  chart:
    spec:
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: loki-system
  interval: 1m0s
  install:
    remediation:
      retries: 3
  values:
    grafana:
      enabled: true
      defaultDashboardsEnabled: true
      ingress:
        enabled: true
        hosts:
          - grafana.example.tld
        tls: []
      grafana.ini:
        auth.anonymous:
          enabled: false
        metrics:
          enabled: true
        server:
          domain: grafana.example.tld
          root_url: http://grafana.example.tld/
    prometheus:
      enabled: true
      isDefault: false
      server:
        persistentVolume:
          enabled: true
          accessModes:
            - ReadWriteOnce
          size: 2Gi
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelector: {}
        serviceMonitorNamespaceSelector: {}
    loki:
      persistence:
        enabled: true
        accessModes:
          - ReadWriteOnce
        size: 2Gi
      service:
        labels:
          scrape-service-metrics: "true"
      serviceMonitor:
        enabled: true
        interval: 15s
